# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ECommerceDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ECommerceDemoApp

  target 'ECommerceDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'ObjectMapper+Realm'
    
  end

  target 'ECommerceDemoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
